### PR TITLE
Add sections structure to readme

### PR DESCRIPTION
**Pull request by vbrazo**
As an attempt to improve our README and add some sections to our book.

### CODE REVIEW

**Comment by vbrazo** [comment]
Do we know how many pages we have if we convert all the examples to `.pdf`?

**Review by dhonx — COMMENTED** [review]
I think it would be better if the struct should be close to the method in one section :thinking:

**Comment by vbrazo** [comment]
Feel free to edit the file. I'm ok to reorder a bit.

**Review by spmse — APPROVED** [review]
I would suggest to have strings/arrays earlier, so every type is introduced and everything following in more advanced sections should be clear without foretaking content.

**Comment by vbrazo** [comment]
Looks good

**Comment by vbrazo** [comment]
let me create the folders and move the files to them so GitBook can create the menu properly.

**Comment by dhonx** [comment]
Please... :+1:  @vbrazo

**Pull request merged**
