### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by StepfenShawn**

### CODE REVIEW

**Comment by dhonx** [comment]
For @v-community/v-community maintainers... please using the `Squash & Merge` Button and please consider to give a good title. Thanks

**Comment by dhonx** [comment]
@stepfencurryxiao Thanks!! But I suggest you to creating a draft pull request instead if you think it's not ready or still in progress.  🙂

**Comment by StepfenShawn** [comment]
OK, I'll finish all the Chinese translations soon :-)

**Review by vbrazo — APPROVED** [review]
👍 💥

**Comment by dhonx** [comment]
@stepfencurryxiao Ping us when you have done  🙂

**Comment by StepfenShawn** [comment]
Hi @dhonx @vbrazo . I finished the Chinese Translation! :-)

**Comment by stepfencurryxiao** [comment]
Hi @dhonx @vbrazo .I finished the Chinese Translation!

**Comment by dhonx** [comment]
Thanks, @stepfencurryxiao !!!

**Comment by StepfenShawn** [comment]
You're welcome.

**Pull request merged**
