### PR TITLE
Translate Operators to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by vbrazo**

### CODE REVIEW

**Review by Delta456 — CHANGES_REQUESTED** [review]
Please see what typo CI says is true or not

**Comment by vbrazo** [comment]
@Delta456 we're good with TypoCI. It's trying to correct the Portuguese words to English :/

**Review by spmse — APPROVED** [review]

**Comment by Delta456** [comment]
> @Delta456 we're good with TypoCI. It's trying to correct the Portuguese words to English :/

Please make the CI to ignore these words

**Comment by vbrazo** [comment]
Ignored 💣

**Review by Delta456 — APPROVED** [review]

**Pull request merged**
