### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by ksaj**
Pluralization. Hope you don't mind all the grammar updates. I'm reading and noticing these things, so I thought it is worth helping the documentation effort.

### CODE REVIEW

**Comment by Delta456** [comment]
We still don't know if there are gonna be more keywords.

**Review by vbrazo — APPROVED** [review]
Let's merge this for now. If V adds more keywords, we'll have to come back and suggest changes.

Thanks for fixing the grammar 👍

**Comment by vbrazo** [comment]
@ksaj could you fix the merge conflicts please?

**Review by dhonx — APPROVED** [review]

**Comment by vbrazo** [comment]
I see `unknown repository`. It looks like you deleted the fork and I think you may have lost the branch, so we should probably consider closing this PR.

**Review by vbrazo — COMMENTED** [review]
I see `unknown repository`. It looks like you deleted the fork and I think you may have lost the branch, so we should probably consider closing this PR.

**Pull request closed without merging**
