### PR TITLE
Restructure language folders

### PR DESCRIPTION
**Pull request by vbrazo**

### CODE REVIEW

**Comment by Delta456** [comment]
Can we tell the spell checker CI to check Portuguese?

**Comment by vbrazo** [comment]
Not sure. In elixirschool, we set this up like [this](https://github.com/elixirschool/elixirschool/blob/master/.typo-ci.yml).

**Comment by Delta456** [comment]
@MikeRogers0 can you add support for Portuguese. @vbrazo can help you if you need.

**Comment by MikeRogers0** [comment]
@Delta456 Of course, no problem :) I'll add it then make a PR to update your `.typo-ci.yml` file :)

**Comment by Delta456** [comment]
> @Delta456 Of course, no problem :) I'll add it then make a PR to update your `.typo-ci.yml` file :)

Love the quick response ❤️

**Review by Delta456 — APPROVED** [review]

**Pull request merged**
