### PR TITLE
example: conditional statements like if, else, else if, for and while.

### PR DESCRIPTION
**Pull request by vbrazo**
This PR is related to https://github.com/v-community/v_by_example/issues/10.

### CODE REVIEW

**Comment by Delta456** [comment]
Why the name `if_statement.md`?  Can't this simply be `condtional_statement.md`?

**Comment by Delta456** [comment]
https://github.com/v-community/v_by_example/blob/392424297bc427e14f5ee7f3fd7f2dff8abc4ec4/examples/conditional_statements/if_statement.md#L53

We don't have markdown support for V yet. Use `go`.

**Comment by vbrazo** [comment]
@Delta456 renamed

**Comment by Delta456** [comment]
https://github.com/v-community/v_by_example/blob/392424297bc427e14f5ee7f3fd7f2dff8abc4ec4/examples/conditional_statements/if_statement.md#L18

https://github.com/v-community/v_by_example/blob/392424297bc427e14f5ee7f3fd7f2dff8abc4ec4/examples/conditional_statements/if_statement.md#L33

Same here

**Comment by Delta456** [comment]
I think a brief introduction to conditional statements would be good.

**Comment by Delta456** [comment]
https://github.com/v-community/v_by_example/blob/58bca4bf791f6ce4672c9272d102c13a7745f2cd/.gitignore#L20

Remove line 17 , 19 and 20

**Review by dhonx — APPROVED** [review]
All looks Great for now !!!  👌

**Review by Delta456 — APPROVED** [review]

**Comment by vbrazo** [comment]
Thanks for reviewing! Merging for now and please feel free to open new PRs to improve this example.

**Pull request merged**
