### PR TITLE
German V

### PR DESCRIPTION
**Pull request by spmse**
Start translation of repo to german.
Already inlcudes: 
 * README
 * CONTRIBUTING
 * copy of structure. 

little rearrangement with the movement of README/CONTRIBUTING*.md to this folder but I think this keeps the tree clean without X readme files.

Still WIP, but think the above point should be discussed for short,

### CODE REVIEW

**Comment by spmse** [comment]
closes #113

**Review by spmse — COMMENTED** [review]
typos are german words mostly, did I do something wrong adding german dictionary to typo-ci? I think same thing like [here](https://github.com/v-community/v_by_example/pull/109#issuecomment-562986196)

**Review by vbrazo — APPROVED** [review]
The `readme` looks good to me. 

I'd split this PR in multiple PRs and just merge the translated part for now. Since we haven't translated anything yet, the `readme` wouldn't have examples link. Just a `todo: translate examples`.

**Comment by spmse** [comment]
ad09a9e closes: #116

**Comment by spmse** [comment]
a8e4af2 and dfa977c will close #117 and #118

**Review by vbrazo — APPROVED** [review]

**Pull request merged**
