### PR TITLE
Localize ja

### PR DESCRIPTION
**Pull request by hachi8833**
Thank you for merging #153.

I added a ja translation.

### CODE REVIEW

**Comment by Delta456** [comment]
Isn't it `jp` instead of `ja`?

**Comment by dhonx** [comment]
Agree with @Delta456. E.g https://jp.vuejs.org/index.html

**Comment by hachi8833** [comment]
OK, I'll change `ja` to `jp`

**Comment by Delta456** [comment]
@hachi8833 please fix merge conflicts

**Comment by hachi8833** [comment]
Unable to resolve the conflicts on the PR...
I close this PR and will send another PR.

**Pull request closed without merging**
