### PR TITLE
Add CONTRIBUTING

### PR DESCRIPTION
**Pull request by vbrazo**

### CODE REVIEW

**Comment by donnisnoni95** [comment]
LGTM for now  👍

**Comment by Delta456** [comment]
I think we should also tell people to make a new branch so that it will not mix things up.

**Review by dhonx — APPROVED** [review]
LGTM for now 👍.

**Comment by dhonx** [comment]
@Delta456 Good idea ... maybe it's more to recommend them to create new branches for changes rather than make changes in the master branch.

**Pull request merged**
